allowBuilds:
  '@prisma/client': set this to true or false
  '@prisma/engines': false
  bcrypt: set this to true or false
  esbuild: set this to true or false
  prisma: false
  sharp: false
  unrs-resolver: false
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
